import _ from 'lodash'

export type PandocFormatContentValue = {
  head: string
}

export type PandocFormatContentKey =
  | 'bibtex'
  | 'biblatex'
  | 'bits'
  | 'commonmark'
  | 'commonmark_x'
  | 'creole'
  | 'csljson'
  | 'csv'
  | 'tsv'
  | 'docbook'
  | 'docx'
  | 'dokuwiki'
  | 'endnotexml'
  | 'epub'
  | 'fb2'
  | 'haddock'
  | 'html'
  | 'ipynb'
  | 'jats'
  | 'jira'
  | 'json'
  | 'latex'
  | 'markdown'
  | 'markdown_mmd'
  | 'markdown_phpextra'
  | 'markdown_strict'
  | 'mediawiki'
  | 'man'
  | 'muse'
  | 'native'
  | 'opml'
  | 'org'
  | 'ris'
  | 'rtf'
  | 'rst'
  | 't2t'
  | 'textile'
  | 'tikiwiki'
  | 'twiki'
  | 'typst'
  | 'vimwiki'
  | 'asciidoc'
  | 'asciidoc_legacy'
  | 'asciidoctor'
  | 'beamer'
  | 'chunkedhtml'
  | 'context'
  | 'docbook4'
  | 'docbook5'
  | 'epub3'
  | 'epub2'
  | 'gfm'
  | 'html5'
  | 'html4'
  | 'icml'
  | 'jats_archiving'
  | 'jats_articleauthoring'
  | 'jats_publishing'
  | 'markua'
  | 'ms'
  | 'odt'
  | 'opendocument'
  | 'pdf'
  | 'plain'
  | 'pptx'
  | 'texinfo'
  | 'slideous'
  | 'slidy'
  | 'dzslides'
  | 'revealjs'
  | 's5'
  | 'tei'
  | 'xwiki'
  | 'zimwiki'

export type PandocFormatContent = Record<
  PandocFormatContentKey,
  PandocFormatContentValue
>
